### ISSUE TITLE
Using MultiIndex series or data frames in MDplot() raise TypeError 

### ISSUE THREAD

**Issue by eafyounian** [TinoGehlert/md_plot#1]
If the Panda's data frame or series has MultiIndex, using `MDplot()` raises the following error:
```
TypeError: Must pass list-like as `names`.
```
The following usage fixes the issue:
```
MDplot(df.reset_index(drop=True))
```

**Comment by TinoGehlert** [comment]
thanks for that bug report, it is fixed with version 0.1.10
